### ISSUE TITLE
Weight plots do not correctly display single point 

### ISSUE THREAD

**Issue by jfkenna** [bobdafish21/discord-bot#1]
**Issue:**
The weight plotting function does not correctly handle users with only a single recorded weight

**Steps to reproduce:**
1. As a new user with no recorded weights, record a new weight
2. Plot the weight graph of the new user

**Expected result:**
A plot containing a single point is displayed

**Actual result:**
An empty plot is displayed

**Comment by bobdafish21** [comment]
not an issue

**Comment by jfkenna** [comment]
We are using this in prod and its crashing pls fix fast

**Comment by bobdafish21** [comment]
past friday 5pm see you monday
